"""add target endpoint fields to runs

Revision ID: 1d52040960dc
Revises: 5cc387d5fa71
Create Date: 2026-07-29 17:16:08.998866

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1d52040960dc"
down_revision: str | None = "5cc387d5fa71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("target_base_url", sa.String(length=512), nullable=True))
    op.add_column("runs", sa.Column("target_instance_type", sa.String(length=64), nullable=True))
    op.add_column("runs", sa.Column("target_arch", sa.String(length=16), nullable=True))
    op.add_column("runs", sa.Column("target_price_per_hour", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "target_price_per_hour")
    op.drop_column("runs", "target_arch")
    op.drop_column("runs", "target_instance_type")
    op.drop_column("runs", "target_base_url")
    # ### end Alembic commands ###
